# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beck < Formula
  desc "Beck — self-hosted PaaS CLI (Incus + Caddy + WireGuard)"
  homepage "https://github.com/beckn-cloud/beck"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/beckn-cloud/beck/releases/download/v0.1.0/beck-v0.1.0-darwin-arm64.tar.gz"
      sha256 "0f413a92443a280dbcfb49e17b67a1690c0663a944bfd543febc178ea09d3037"

      def install
        bin.install "beck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beckn-cloud/beck/releases/download/v0.1.0/beck-v0.1.0-darwin-amd64.tar.gz"
      sha256 "557176193c2d0deab61483d4a6e5a5a161cd3adff324a28cc4b3f082d8b8844f"

      def install
        bin.install "beck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beckn-cloud/beck/releases/download/v0.1.0/beck-v0.1.0-linux-arm64.tar.gz"
      sha256 "5640329af9f13ffa87ca0e07eba947d623c9c9e2a737cbcacc0c47ae096af3cb"

      def install
        bin.install "beck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beckn-cloud/beck/releases/download/v0.1.0/beck-v0.1.0-linux-amd64.tar.gz"
      sha256 "5b68c445961d25c75125d1c2bb544facb07bac567679ebfa27e068c5857c8f15"

      def install
        bin.install "beck"
      end
    end
  end

  test do
    system "#{bin}/beck", "version"
  end
end